# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.0.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.0.1/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/tbcdigital/Developer/lci-future/lci

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/tbcdigital/Developer/lci-future/lci

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.0.1/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.0.1/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.0.1/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.0.1/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.0.1/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.0.1/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/local/Cellar/cmake/3.0.1/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/tbcdigital/Developer/lci-future/lci/CMakeFiles /Users/tbcdigital/Developer/lci-future/lci/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/tbcdigital/Developer/lci-future/lci/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named docs

# Build rule for target.
docs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 docs
.PHONY : docs

# fast build rule for target.
docs/fast:
	$(MAKE) -f CMakeFiles/docs.dir/build.make CMakeFiles/docs.dir/build
.PHONY : docs/fast

#=============================================================================
# Target rules for targets named lci

# Build rule for target.
lci: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lci
.PHONY : lci

# fast build rule for target.
lci/fast:
	$(MAKE) -f CMakeFiles/lci.dir/build.make CMakeFiles/lci.dir/build
.PHONY : lci/fast

binding.o: binding.c.o
.PHONY : binding.o

# target to build an object file
binding.c.o:
	$(MAKE) -f CMakeFiles/lci.dir/build.make CMakeFiles/lci.dir/binding.c.o
.PHONY : binding.c.o

binding.i: binding.c.i
.PHONY : binding.i

# target to preprocess a source file
binding.c.i:
	$(MAKE) -f CMakeFiles/lci.dir/build.make CMakeFiles/lci.dir/binding.c.i
.PHONY : binding.c.i

binding.s: binding.c.s
.PHONY : binding.s

# target to generate assembly for a file
binding.c.s:
	$(MAKE) -f CMakeFiles/lci.dir/build.make CMakeFiles/lci.dir/binding.c.s
.PHONY : binding.c.s

error.o: error.c.o
.PHONY : error.o

# target to build an object file
error.c.o:
	$(MAKE) -f CMakeFiles/lci.dir/build.make CMakeFiles/lci.dir/error.c.o
.PHONY : error.c.o

error.i: error.c.i
.PHONY : error.i

# target to preprocess a source file
error.c.i:
	$(MAKE) -f CMakeFiles/lci.dir/build.make CMakeFiles/lci.dir/error.c.i
.PHONY : error.c.i

error.s: error.c.s
.PHONY : error.s

# target to generate assembly for a file
error.c.s:
	$(MAKE) -f CMakeFiles/lci.dir/build.make CMakeFiles/lci.dir/error.c.s
.PHONY : error.c.s

inet.o: inet.c.o
.PHONY : inet.o

# target to build an object file
inet.c.o:
	$(MAKE) -f CMakeFiles/lci.dir/build.make CMakeFiles/lci.dir/inet.c.o
.PHONY : inet.c.o

inet.i: inet.c.i
.PHONY : inet.i

# target to preprocess a source file
inet.c.i:
	$(MAKE) -f CMakeFiles/lci.dir/build.make CMakeFiles/lci.dir/inet.c.i
.PHONY : inet.c.i

inet.s: inet.c.s
.PHONY : inet.s

# target to generate assembly for a file
inet.c.s:
	$(MAKE) -f CMakeFiles/lci.dir/build.make CMakeFiles/lci.dir/inet.c.s
.PHONY : inet.c.s

interpreter.o: interpreter.c.o
.PHONY : interpreter.o

# target to build an object file
interpreter.c.o:
	$(MAKE) -f CMakeFiles/lci.dir/build.make CMakeFiles/lci.dir/interpreter.c.o
.PHONY : interpreter.c.o

interpreter.i: interpreter.c.i
.PHONY : interpreter.i

# target to preprocess a source file
interpreter.c.i:
	$(MAKE) -f CMakeFiles/lci.dir/build.make CMakeFiles/lci.dir/interpreter.c.i
.PHONY : interpreter.c.i

interpreter.s: interpreter.c.s
.PHONY : interpreter.s

# target to generate assembly for a file
interpreter.c.s:
	$(MAKE) -f CMakeFiles/lci.dir/build.make CMakeFiles/lci.dir/interpreter.c.s
.PHONY : interpreter.c.s

lexer.o: lexer.c.o
.PHONY : lexer.o

# target to build an object file
lexer.c.o:
	$(MAKE) -f CMakeFiles/lci.dir/build.make CMakeFiles/lci.dir/lexer.c.o
.PHONY : lexer.c.o

lexer.i: lexer.c.i
.PHONY : lexer.i

# target to preprocess a source file
lexer.c.i:
	$(MAKE) -f CMakeFiles/lci.dir/build.make CMakeFiles/lci.dir/lexer.c.i
.PHONY : lexer.c.i

lexer.s: lexer.c.s
.PHONY : lexer.s

# target to generate assembly for a file
lexer.c.s:
	$(MAKE) -f CMakeFiles/lci.dir/build.make CMakeFiles/lci.dir/lexer.c.s
.PHONY : lexer.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/lci.dir/build.make CMakeFiles/lci.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/lci.dir/build.make CMakeFiles/lci.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/lci.dir/build.make CMakeFiles/lci.dir/main.c.s
.PHONY : main.c.s

parser.o: parser.c.o
.PHONY : parser.o

# target to build an object file
parser.c.o:
	$(MAKE) -f CMakeFiles/lci.dir/build.make CMakeFiles/lci.dir/parser.c.o
.PHONY : parser.c.o

parser.i: parser.c.i
.PHONY : parser.i

# target to preprocess a source file
parser.c.i:
	$(MAKE) -f CMakeFiles/lci.dir/build.make CMakeFiles/lci.dir/parser.c.i
.PHONY : parser.c.i

parser.s: parser.c.s
.PHONY : parser.s

# target to generate assembly for a file
parser.c.s:
	$(MAKE) -f CMakeFiles/lci.dir/build.make CMakeFiles/lci.dir/parser.c.s
.PHONY : parser.c.s

tokenizer.o: tokenizer.c.o
.PHONY : tokenizer.o

# target to build an object file
tokenizer.c.o:
	$(MAKE) -f CMakeFiles/lci.dir/build.make CMakeFiles/lci.dir/tokenizer.c.o
.PHONY : tokenizer.c.o

tokenizer.i: tokenizer.c.i
.PHONY : tokenizer.i

# target to preprocess a source file
tokenizer.c.i:
	$(MAKE) -f CMakeFiles/lci.dir/build.make CMakeFiles/lci.dir/tokenizer.c.i
.PHONY : tokenizer.c.i

tokenizer.s: tokenizer.c.s
.PHONY : tokenizer.s

# target to generate assembly for a file
tokenizer.c.s:
	$(MAKE) -f CMakeFiles/lci.dir/build.make CMakeFiles/lci.dir/tokenizer.c.s
.PHONY : tokenizer.c.s

unicode.o: unicode.c.o
.PHONY : unicode.o

# target to build an object file
unicode.c.o:
	$(MAKE) -f CMakeFiles/lci.dir/build.make CMakeFiles/lci.dir/unicode.c.o
.PHONY : unicode.c.o

unicode.i: unicode.c.i
.PHONY : unicode.i

# target to preprocess a source file
unicode.c.i:
	$(MAKE) -f CMakeFiles/lci.dir/build.make CMakeFiles/lci.dir/unicode.c.i
.PHONY : unicode.c.i

unicode.s: unicode.c.s
.PHONY : unicode.s

# target to generate assembly for a file
unicode.c.s:
	$(MAKE) -f CMakeFiles/lci.dir/build.make CMakeFiles/lci.dir/unicode.c.s
.PHONY : unicode.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... docs"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... lci"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... binding.o"
	@echo "... binding.i"
	@echo "... binding.s"
	@echo "... error.o"
	@echo "... error.i"
	@echo "... error.s"
	@echo "... inet.o"
	@echo "... inet.i"
	@echo "... inet.s"
	@echo "... interpreter.o"
	@echo "... interpreter.i"
	@echo "... interpreter.s"
	@echo "... lexer.o"
	@echo "... lexer.i"
	@echo "... lexer.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... parser.o"
	@echo "... parser.i"
	@echo "... parser.s"
	@echo "... tokenizer.o"
	@echo "... tokenizer.i"
	@echo "... tokenizer.s"
	@echo "... unicode.o"
	@echo "... unicode.i"
	@echo "... unicode.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

